### ISSUE TITLE
mtkrilw

### ISSUE THREAD

**Issue by fire855** [axet/android_device_mt6592#2]
Hello axet,

can you explain why the mtkrilw code is needed? Because on developments for other mtk devices with other processor this wasn't needed. I don't understand the code on some things and is 3G working in your code?

Greetings
Fire

**Comment by axet** [comment]
mtk uses it's own RIL command. when you make call, hangup or answer calls they have some "better" sollution then use original RIL commands.

mtkrilw task is to ignore unknown commands and loop them with original RIL commands.

As I can tell mediatek programmers are terrable with coding, versioning.
