### ISSUE TITLE
mtkrilw

### ISSUE THREAD

**Issue by fire855** [axet/android_device_mt6592#4]
Hello,

I found a problem with your libmtkrilw. Sometimes when I do calls it's making problems.
Error: http://pastebin.com/5rChxV9f
Seems to be a problem with libmtkrilw or?

Regards
Fire

**Comment by axet** [comment]
Please explain your findings by following events, error messages and library calls.

**Comment by fire855** [comment]
I'm working now on CyanogenMod 12 and there I have the problem that ril is crashing on calling and then I get this errors in logcat: http://pastebin.com/5rChxV9f

The problem is when libmtkrilw is crashing and then restarting it's trying to register the sockets but they are already registered.
https://github.com/axet/android_device_mt6592/blob/master/mtkrilw/mtkrilw.c#L248
I think we need here a check if the sockets are already registered. What do you think?

**Comment by fire855** [comment]
I will try to use your MTKRIL.java class. Maybe there is a problem with mine.

**Comment by fire855** [comment]
Here radio log: http://pastebin.com/eCNHFqEE

I called 1234. It starts in 3060.

Maybe that's the problem:
E/RILJ    ( 1107): Hit EOS reading message length
I/RILJ    ( 1107): Disconnected from 'rild' socket

**Comment by fire855** [comment]
I fixed this with removing mtkrilw and only using mtk-ril.so
